### ISSUE TITLE
When start the project, popup page is blank, Chrome reports error: process in not defined

### ISSUE THREAD

**Issue by yaowang908** [extend-chrome/ts-react-boilerplate#2]
### Google search terms

Process is not defined + rollup

### Describe the bug

Start the project, load unpacked extension in Chrome.
Click the extension, blank page shows up, and Chrome reports error: process is not defined.

### How do we reproduce?

Start the project, load unpacked extension in Chrome. Click the extension.

### Expected behavior

The actual popup and no error.

### Actual behavior

Blank page

### Please complete the following information:

- Library Version:
- Operating System:
- Browser:
- Node Version:

### Additional context

I actually fixed this problem by adding @rollup/plugin-replace. My code is [here](https://github.com/yaowang908/ts-react-boilerplate). 
Let me know if I should submit this PR.

**Comment by atharva-bhange** [comment]
Thanks a lot worked for me !! It would be great if you could create PR.

**Comment by AmySteam** [comment]
@yaowang908 Thanks for the PR 🎉 . Closing this issue.
